### ISSUE TITLE
Deprecated Function for "comment_whitelist

### ISSUE THREAD

**Issue by lanaphillips** [joshuadavidnelson/disable-blog#71] opened 2023-08-01 20:23 UTC
This error only shows up if this plugin is enabled. This is also on a brand new WP install.

Function update_option was called with an argument that is deprecated since version 5.5.0! The "comment_whitelist" option key has been renamed to "comment_previously_approved". in /home/758708.cloudwaysapps.com/ymtwarqkbm/public_html/wp-includes/functions.php on line 5697

**Comment by joshuadavidnelson** [comment] 2023-08-07 13:10
Duplicate of #72, closing

**Closed as completed by joshuadavidnelson** 2023-08-07 13:10 UTC
